name: neomutt CI

on: 
  workflow_dispatch:
    branches: 
     - '*'
     - '!flatcap'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner  }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1  
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: build.Dockerfile
        platforms: linux/amd64
        push: false